name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: build
      run: |
        rm -rf ./node_modules
        rm -rf ./.next
        yarn
        yarn build
    - name: deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd ${{ secrets.SSH_DEPLOYMENT_PATH }}
          git fetch -a -p
          git reset --hard origin/master
          yarn
          node pre-deploy.js
          yarn build
          pm2 restart ${{ secrets.PM2_ID_PROD }} -s
